### ISSUE TITLE
Testmail not working

### ISSUE THREAD

**Issue by tgrueber** [w-vision/NewsletterDefinitionBundle#1]
Hi Dominik, is it possible to use NewsletterDefinition and sending a testmail? I always get the message like "message could not be sent. Please contact your admin!"?

**Comment by tgrueber** [comment]
yes. That worked! Pimcore Version is 5.2.2 by the way.

**Comment by tgrueber** [comment]
Hi, do you have a tip how to solve the problem?

**Comment by dpfaffenbauer** [comment]
need to look at that when I have time...

**Comment by tgrueber** [comment]
Can this be the problem: Warning appears on classes-rebuild:
`WARNING   [php] Warning: Cannot declare class \Pimcore\Document\Newsletter\AddressSourceAdapter\NewsletterDefinition, because the name is already in use ["exception" => ErrorException { …}] []`

**Comment by skrahlQW** [comment]
I solved the problem by removing the line

```
class_alias(DefinitionAddressSourceAdapter::class, '\\Pimcore\\Document\\Newsletter\\AddressSourceAdapter\\NewsletterDefinition');
```

from NewletterDefinitionBundle.php and adding the following lines to app/config/services.yml and app/config/config.yml:

```
#services.yml:
pimcore.document.newsletter.factory.newsletter_definition:
        class: Pimcore\Document\Newsletter\DefaultAddressSourceAdapterFactory
        arguments:
          - 'NewsletterDefinitionBundle\AddressSourceAdapater\DefinitionAddressSourceAdapter'
```

```
#config.yml:
newsletter:
        source_adapters:
            newsletterDefinition: pimcore.document.newsletter.factory.newsletter_definition
```

I also found a little bug in NewsletterDefinitionController.php in line 119: "parent" has to be changed to "parentId" to make this filter work.

Now everything is working fine.

I will add this changes to a new branch and provide a pull request.
